const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding SQLite database...\n');

  const passwordHash = await bcrypt.hash('growzylead@366', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@linsinfotech.in' },
    update: {},
    create: {
      email: 'admin@linsinfotech.in',
      password_hash: passwordHash,
      name: 'Admin',
      role: 'admin',
    },
  });
  console.log(`✅ Admin user created: ${admin.email}`);

  const sampleLeads = [
    {
      company_name: 'Sri Krishna Textiles',
      industry: 'Textiles & Manufacturing',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      tab_category: 'no_website',
      source: 'google_places',
      lead_score: 75,
      pain_points: JSON.stringify(['No website detected', 'Has physical location but no web presence', 'Uses Instagram as storefront']),
      pitch_angle: 'No web presence — full website build',
      outreach_status: 'new',
      contact_name: 'Raj Kumar',
      contact_phone: '+91 98765 43210',
      contact_source: 'google_business_profile',
      contact_confidence: 'verified',
      tab_data: JSON.stringify({ primary_social_link: 'https://instagram.com/srikrishnatextiles', employee_count_estimate: 15, has_physical_location: true }),
    },
    {
      company_name: 'Annapurna Restaurant',
      industry: 'Restaurant & Food',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      tab_category: 'no_website',
      source: 'justdial',
      lead_score: 68,
      pain_points: JSON.stringify(['No website detected', 'Listed on Justdial with no website link']),
      pitch_angle: 'No web presence — full website build',
      outreach_status: 'new',
      contact_phone: '+91 87654 32109',
      contact_source: 'justdial_listing',
      contact_confidence: 'verified',
      tab_data: JSON.stringify({ has_physical_location: true, employee_count_estimate: 8 }),
    },
    {
      company_name: 'Elite Fitness Studio',
      industry: 'Health & Fitness',
      city: 'Dubai',
      country: 'UAE',
      region: 'international',
      tab_category: 'no_website',
      source: 'google_places',
      lead_score: 72,
      pain_points: JSON.stringify(['No website detected', 'Uses Facebook page as storefront']),
      pitch_angle: 'No web presence — full website build',
      outreach_status: 'new',
      tab_data: JSON.stringify({ primary_social_link: 'https://facebook.com/elitefitnessdxb', has_physical_location: true, employee_count_estimate: 6 }),
    },
    {
      company_name: 'TechnoSoft Solutions',
      industry: 'IT Services',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      website_url: 'https://technosoftsolutions.in',
      tab_category: 'weak_seo',
      source: 'manual',
      lead_score: 82,
      pain_points: JSON.stringify(['Missing meta description', 'No sitemap.xml', 'No structured data', 'Poor PageSpeed: 34/100']),
      pitch_angle: 'Website exists but invisible on Google — SEO retainer',
      outreach_status: 'contacted',
      contact_email: 'info@technosoftsolutions.in',
      contact_source: 'site_contact_page',
      contact_confidence: 'verified',
      tab_data: JSON.stringify({ pagespeed_score: 34, seo_score: 25, indexed_pages_count: 3, top_missing_seo_items: ['No meta description', 'No sitemap.xml', 'No schema markup', 'Missing canonical'] }),
    },
    {
      company_name: 'GreenLeaf Organics',
      industry: 'Agriculture & Food',
      city: 'Madurai',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      website_url: 'https://greenleaforganics.co.in',
      tab_category: 'weak_seo',
      source: 'directory',
      lead_score: 70,
      pain_points: JSON.stringify(['No robots.txt', 'Missing viewport tag', 'No blog content']),
      pitch_angle: 'Website exists but invisible on Google — SEO retainer',
      outreach_status: 'new',
      tab_data: JSON.stringify({ pagespeed_score: 55, seo_score: 40, top_missing_seo_items: ['No robots.txt', 'Missing viewport', 'No blog'] }),
    },
    {
      company_name: 'MedCare Hospitals',
      industry: 'Healthcare',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      website_url: 'https://medcarehospitals.in',
      tab_category: 'agentic_ai',
      source: 'manual',
      lead_score: 85,
      pain_points: JSON.stringify(['No chatbot detected', 'Phone-only appointment booking', 'No CRM or automation tools detected', 'Healthcare — high-ROI industry for AI automation']),
      pitch_angle: 'Replace manual processes with AI agents',
      outreach_status: 'meeting_booked',
      contact_name: 'Dr. Priya Sharma',
      contact_email: 'admin@medcarehospitals.in',
      contact_phone: '+91 44 2345 6789',
      contact_source: 'site_contact_page',
      contact_confidence: 'verified',
      tab_data: JSON.stringify({ detected_manual_workflows: ['Phone-only appointment booking', 'Manual patient reminders', 'Paper-based billing'], suggested_use_case: 'AI appointment scheduling & patient reminder bot', automation_roi_note: 'High ROI: automate 3+ manual workflows' }),
    },
    {
      company_name: 'PropFirst Real Estate',
      industry: 'Real Estate',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
      region: 'local',
      website_url: 'https://propfirst.in',
      tab_category: 'agentic_ai',
      source: 'manual',
      lead_score: 72,
      pain_points: JSON.stringify(['WhatsApp-only lead follow-up', 'No chatbot detected', 'Real Estate — high-ROI industry for AI automation']),
      pitch_angle: 'Replace manual processes with AI agents',
      outreach_status: 'new',
      tab_data: JSON.stringify({ detected_manual_workflows: ['WhatsApp-only lead qualification', 'Manual property matching'], suggested_use_case: 'AI lead qualification & property recommendation bot' }),
    },
    {
      company_name: 'Classic Furniture House',
      industry: 'Retail & Furniture',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      website_url: 'https://classicfurniturehouse.com',
      tab_category: 'maintenance',
      source: 'manual',
      lead_score: 78,
      pain_points: JSON.stringify(['Copyright year 2021 (4 years stale)', '5 broken links', 'SSL expires in 15 days', 'Running on WordPress 5.8 (outdated)']),
      pitch_angle: 'Site is live but unmaintained — maintenance care plan',
      outreach_status: 'new',
      tab_data: JSON.stringify({ cms_detected: 'WordPress', last_content_update_estimate: '2021', broken_link_count: 5, ssl_status: 'valid', ssl_expiry: '2026-08-26' }),
    },
    {
      company_name: 'Lakshmi Distributors',
      industry: 'Distribution & Wholesale',
      city: 'Trichy',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      tab_category: 'erp',
      source: 'manual',
      lead_score: 80,
      pain_points: JSON.stringify(['Currently using spreadsheet-based record keeping', 'Multi-location business (4 branches) — high ERP ROI', 'Suggested modules: Inventory, Billing/GST, Procurement']),
      pitch_angle: 'Run this on one system instead of five spreadsheets — custom ERP',
      outreach_status: 'responded',
      contact_name: 'Karthik Rajan',
      contact_phone: '+91 76543 21098',
      contact_source: 'justdial_listing',
      contact_confidence: 'verified',
      tab_data: JSON.stringify({ current_recordkeeping: 'spreadsheet', branch_count: 4, suggested_erp_modules: ['Inventory', 'Billing/GST', 'Procurement'] }),
    },
    {
      company_name: 'Sunrise School Group',
      industry: 'Education',
      city: 'Salem',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      tab_category: 'erp',
      source: 'manual',
      lead_score: 75,
      pain_points: JSON.stringify(['Multi-location business (3 branches)', 'Education — strong ERP use case', 'Paper-based attendance and fee collection']),
      pitch_angle: 'Run this on one system instead of five spreadsheets — custom ERP',
      outreach_status: 'new',
      tab_data: JSON.stringify({ current_recordkeeping: 'paper', branch_count: 3, suggested_erp_modules: ['Student Management', 'Fee Collection', 'Attendance', 'HR'] }),
    },
    {
      company_name: 'Spice Bazaar Online',
      industry: 'E-commerce & Food',
      city: 'Kochi',
      state: 'Kerala',
      country: 'India',
      region: 'local',
      website_url: 'https://spicebazaaronline.in',
      tab_category: 'ecommerce',
      source: 'manual',
      lead_score: 65,
      pain_points: JSON.stringify(['Missing: Cart abandonment recovery', 'Missing: Multiple payment gateways', 'No mobile checkout optimization']),
      pitch_angle: 'Modernize your e-commerce — conversion optimization',
      outreach_status: 'new',
      tab_data: JSON.stringify({ current_platform: 'WooCommerce', missing_features: ['Cart abandonment recovery', 'Multiple payment gateways', 'Inventory sync'], has_mobile_checkout: false }),
    },
    {
      company_name: 'Heritage Hotels Group',
      industry: 'Hospitality',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
      region: 'local',
      website_url: 'http://heritagehotelsgroup.com',
      tab_category: 'legacy_tech',
      source: 'manual',
      lead_score: 70,
      pain_points: JSON.stringify(['Legacy: jQuery-only (no modern framework)', 'Legacy: Outdated Bootstrap version', 'Site is not using HTTPS — security risk']),
      pitch_angle: 'Full tech stack rebuild — modern, secure, fast',
      outreach_status: 'new',
      tab_data: JSON.stringify({ detected_legacy_stack: ['jQuery-only', 'Bootstrap 2', 'No HTTPS'], has_https: false }),
    },
    {
      company_name: 'Tamil Nadu State IT Dept',
      industry: 'Government',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      region: 'local',
      tab_category: 'rfp_watch',
      source: 'manual',
      lead_score: 85,
      pain_points: JSON.stringify(['Deadline in 21 days', 'Matches: Web Development, Database Management, Training Portal']),
      pitch_angle: null,
      outreach_status: 'new',
      notes: 'RFP for state education portal similar to Vidya Setu project',
      tab_data: JSON.stringify({ rfp_source: 'gem.gov.in', deadline: '2026-09-01', budget_range: '₹25L - ₹50L', matching_capabilities: ['Web Development', 'Database Management', 'Training Portal'] }),
    },
  ];

  for (const lead of sampleLeads) {
    await prisma.lead.create({ data: lead });
  }

  console.log(`✅ Created ${sampleLeads.length} sample leads across all tabs`);
  console.log('\n🎉 Seeding complete!\n');
}

main()
  .catch((e) => {
    console.error('Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
